CWD := $(shell pwd)
OS := $(shell uname -s)
LIBS = lib/ameba lib/clang
WGPU_ARTIFACTS := vendor/webgpu.h vendor/wgpu.h

default: all

lint: shards
	bin/ameba
	crystal tool format -e src/lib-wgpu.cr --check
.PHONY: lint

test:
	crystal spec
.PHONY: test

clean:
	rm -f examples/headless
	rm -f examples/*.dwarf
	rm -rf lib
.PHONY: clean

all: vendor-libs shards
.PHONY: all

src/lib-wgpu.cr: lib/clang/bin/c2cr ${WGPU_ARTIFACTS}
	@echo "# AUTOGENERATED: DO NOT EDIT!" > src/lib-wgpu.cr
	@echo "@[Link(ldflags: \"-L#{__DIR__}/../bin/libs -lwgpu_native\")]" >> src/lib-wgpu.cr
	lib/clang/bin/c2cr -Ivendor webgpu.h --remove-enum-prefix=WGPU >> src/lib-wgpu.cr
	lib/clang/bin/c2cr -Ivendor wgpu.h --remove-enum-prefix=WGPU >>
	@echo "Remember to follow instructions in src/lib-wgpu.cr"

lib/clang/bin/c2cr: lib/clang
	@cd lib/clang && shards build --release --ignore-crystal-version

shards:
	shards install --ignore-crystal-version
.PHONY: shards

${LIBS}:
	shards install --ignore-crystal-version

vendor-libs: vendor-wgpu
.PHONY: vendor-libs

# TODO: Add OS checks for Linux and Windows
ifeq (${OS},Darwin)
	WGPU_ARTIFACTS += bin/libs/libwgpu_native.dylib
endif
vendor-wgpu: ${WGPU_ARTIFACTS}
.PHONY: vendor-wgpu

# TODO: Execute with --release for release builds
${WGPU_ARTIFACTS}: vendor/wgpu.cr native.lock.yml
	crystal vendor/wgpu.cr

# macOS troubleshooting:
# https://stackoverflow.com/a/17704255/1363247
# https://developer.apple.com/forums/thread/656303
# https://www.oreilly.com/library/view/modding-mac-os/0596007094/ch04s05.html

example-headless: vendor-libs
	crystal build examples/headless.cr -o examples/headless
ifeq (${OS},Darwin)
	@echo "Fixing up libwgpu_native dylib path…"
	@install_name_tool -change /Users/runner/work/wgpu-native/wgpu-native/target/debug/deps/libwgpu_native.dylib @executable_path/../../Frameworks/libwgpu_native.dylib examples/headless
	@otool -L examples/headless | grep wgpu
	@rm -rf "examples/headless.app"
	@scripts/appify.sh examples/headless
	@mkdir -p "headless.app/Frameworks"
	@cp bin/libs/libwgpu_native.dylib "headless.app/Frameworks"
	@cp examples/Info.plist "headless.app/Contents"
	@mv -f "headless.app" examples
else
	env LD_LIBRARY_PATH=${CWD}/bin/libs examples/headless
endif
.PHONY: example-headless

example-triangle: vendor-libs
	env LD_LIBRARY_PATH=${CWD}/bin/libs crystal build examples/triangle.cr -o examples/triangle
.PHONY: example-triangle
