CWD := $(shell pwd)
OS := $(shell uname -s)
LIBS = lib/ameba lib/clang

default: all

lint:
	bin/ameba
	crystal tool format --check
.PHONY: lint

test:
	crystal spec
.PHONY: test

clean:
	rm -f examples/headless
	rm -f examples/*.dwarf
	rm -rf lib
	rm src/lib-wgpu.cr
.PHONY: clean

all: vendor-libs shards src/lib-wgpu.cr
.PHONY: all

src/lib-wgpu.cr: lib/clang/bin/c2cr vendor/wgpu.h
	@echo "# AUTOGENERATED: DO NOT EDIT!" > src/lib-wgpu.cr
	@echo "# Use `UInt32` for interop enums because rust enums are tagged unions" > src/lib-wgpu.cr
	@echo "@[Link(ldflags: \"-L#{__DIR__}/../bin/libs -lwgpu_native\")]" > src/lib-wgpu.cr
	lib/clang/bin/c2cr -Ivendor wgpu.h --remove-enum-prefix=WGPU >> src/lib-wgpu.cr

lib/clang/bin/c2cr: lib/clang
	@cd lib/clang && shards build --release

shards: ${LIBS}
.PHONY: shards

${LIBS}: shard.yml
	shards install

vendor-libs: vendor-wgpu
.PHONY: vendor-libs

WGPU_ARTIFACTS := vendor/webgpu.h vendor/wgpu.h
# TODO: Add OS checks for Linux and Windows
ifeq (${OS},Darwin)
	WGPU_ARTIFACTS += bin/libs/libwgpu_native.dylib
endif
vendor-wgpu: ${WGPU_ARTIFACTS}
.PHONY: vendor-wgpu

# TODO: Execute with --release for release builds
${WGPU_ARTIFACTS}:
	crystal vendor/wgpu.cr

example-headless: vendor-libs src/lib-wgpu.cr
	env LD_LIBRARY_PATH=${CWD}/bin/libs crystal examples/headless.cr --verbose
.PHONY: example-headless

example-triangle: vendor-libs src/lib-wgpu.cr
	env LD_LIBRARY_PATH=${CWD}/bin/libs crystal examples/triangle.cr
.PHONY: example-triangle
